---

# Run with ansible-playbook -i vagrant_hosts.cfg vagrant_playbook.yml
- hosts: vagrant
  become: yes
  become_method: sudo
  gather_facts: yes
  pre_tasks:
    - include: senaite_pre_tasks.yml
  tasks:
#    - include: senaite_tasks.yml
    - include: senaite_haproxy.yml
  roles:
#    # SENAITE PLONE
#    - role: plone.plone_server
#      plone_config: "{{ senaite_plone_config[0] }}"
